### ISSUE TITLE
Documentation: Introducing legacy Abaqus/UMAT implementations in MFrontGallery

### ISSUE THREAD

**Issue by kuateric** [thelfer/MFrontGallery#17]
Hi @thelfer, 
here is a thread to discuss about the documentation of the umat wrapper in mfront. 
The state of your report can be found [here](https://thelfer.github.io/MFrontGallery/web/SmallStrainUmatWrapper.html).

**Comment by kuateric** [comment]
I read the report and I like it. Do you expect me to contribute somewhere ? 
I think it should be better to remove the section 3 about the treatment of the material properties and write a new documentation about this important topic. The treatment of material properties is not just relevant for the wrappers but for all behaviours in MfrontGallery. We can just introduce the two approaches in this documentation in few sentences and refer to the documentation that we must carried out later on. This helps to have a better visibility about the topic

**Comment by thelfer** [comment]
@kuateric Thanks for the feed-backs.

> Do you expect me to contribute somewhere ?

Well. For the moment feed-backs and corrections :)

> I think it should be better to remove the section 3 about the treatment of the material properties and write a new documentation about this important topic.

It is important and I plan to add a section about this in the "Best practices" page. But examples are more efficient that abstract discussion  and I like my tutorials to be more or less self-contained. Moreover, the fact that one shall pass a continuous array of memory the the `UMAT` subroutine deserves special care and trade-offs have to be made between ease of implementation (declaration of an array of material properties/parameters) and ease of use for the final user.

All in all, I do consider that this point is really about wrapping a "good" wrapper, if we agree that the definition of good depends on the targeted usage.
