### ISSUE TITLE
Request to include of Modified Cam Clay model

### ISSUE THREAD

**Issue by nagelt** [thelfer/MFrontGallery#3]
We'd like to include the modified Cam Clay model with the following implementation into the MFrontGallery. I've attached a zip file containing the *.mfront file, two *.py files containing MTests and creating the associated plots, and a Doku folder with a LaTeX based documentation on the implementation and the tests.
The documentation and code pieces are also part of the current OpenGeoSys master branch. Let us know if there are any queries.

@thelfer

[MCC_bundle.zip](https://github.com/thelfer/MFrontGallery/files/7719596/MCC_bundle.zip)

**Comment by thelfer** [comment]
Hi @nagelt 

I created branch `th/work_issue_3` to work on this issue.

I make a few changes:

1. I renamed the behaviour as `SemiImplicitModifiedCamClay_OpenGeoSys2020`.
2. I remove the hack used to initialize the initial state and the assocatied material properties. I am still working on this issue <https://github.com/thelfer/MFrontGenericInterfaceSupport/issues/50> for version 4.1 which would make such hacks useless.

Thomas

**Comment by thelfer** [comment]
@nagelt Concerning the tests:

1. `python` tests are ok, but I would remove the dependency to matplot lib or at least make it optional (try/except around the import of `matplotlib` and conditionally generate the figures
2. I would need reference results.

## Using the `results` array

1. You can save them in a txt file using numpy API.
2. It would be nice if you could set up the non regression tests by loading the values from the reference file generated at Step 1 and compare the results (don't know how to do it with numpy, but it is probably easy to do).

## Using `MTest` ouptuts

In this case, would you rerun the tests by:
    - setting an output file using the `setOutputFileName` method
    - setting a 14 digits outputs using the `setOutputFilePrecision` method
    - print the current state before the resolution and at the end of each time step using the `printOutput` method

**Comment by nagelt** [comment]
@thelfer Just made a corresponding pull request. Let me know if that suffices or you need more.

**Comment by thelfer** [comment]
@nagelt Many thanks. I merged the PR, just to see how its works.

BTW, just started the conversion of the documentation: <https://thelfer.github.io/MFrontGallery/web/SemiImplicitModifiedCamClay_OpenGeoSys2020.html>

Still have to convert several figures, tables and references.

**Comment by nagelt** [comment]
Nice ... I hope the tensor notation definitions don't create too much trouble ... I had tried a Pandoc conversion to markdown, but received some package errors I didn't yet take care of ...

**Comment by thelfer** [comment]
To be honest, it took me about one hour for this result. I don't think that used pandoc to convert tex to markdown is really useful.
By hand conversion leads to a more satisfying result.

**Comment by thelfer** [comment]
@nagelt Please see this commit: 
<https://github.com/thelfer/MFrontGallery/commit/6111fd2abddab350c04fece08f5d157d98e36013>
 which shows how to enable the provided tests for the `aster` and `generic` interfaces.

**Comment by thelfer** [comment]
Hi @nagelt,

would you review this page: <https://thelfer.github.io/MFrontGallery/web/SemiImplicitModifiedCamClay_OpenGeoSys2020.html>

**Comment by nagelt** [comment]
> Hi @nagelt,
> 
> would you review this page: https://thelfer.github.io/MFrontGallery/web/SemiImplicitModifiedCamClay_OpenGeoSys2020.html

I did have a brief look and made a PR. Will check more detailed another time.

**Comment by thelfer** [comment]
@nagelt

So now we have a proper documentation and some tests. Do you want to update the  `python` tests or shall we stop here and close the PR ?

For me both are fine and the main goal is achieved: you now have a much deeper understanding of what `MFrontGallery` is.

**Comment by nagelt** [comment]
> @nagelt
> 
> So now we have a proper documentation and some tests. Do you want to update the  `python` tests or shall we stop here and close the PR ?
> 
> For me both are fine and the main goal is achieved: you now have a much deeper understanding of what `MFrontGallery` is.

I think we're fine. No need for the additional Python tests. They won't be lost and can be transferred any time if need be.

**Comment by nagelt** [comment]
And many thanks, @thelfer . It's always a pleasure.

**Comment by thelfer** [comment]
Merged with `master`, closing the issue !
