### ISSUE TITLE
Debug option in the cmake

### ISSUE THREAD

**Issue by jfauque** [thelfer/MFrontGallery#34]
Hello,  
It could be nice to have a debug option in the cmake to compile behavior laws in debug mode.  
The option GenerateMTestFileOnFailure would also be interesting in the same idea.
Thanks,
Jules

**Comment by thelfer** [comment]
## Debug options

- `enable-mfront-debug-mode`: appends --debug to the options passed to `MFront`.
- `enable-mtest-file-generation-on-failure`: appends  `--@GenerateMTestFileOnFailure=true` to the options passed to `MFront`  when compiling behaviours.
