### ISSUE TITLE
Strain energy for Signorini behaviour is not consistent

### ISSUE THREAD

**Issue by octave-user** [thelfer/MFrontGallery#49]
Dear Thomas Helfer,

It seems that the strain energy function for the Signorini behaviour is not consistent with the stress tensor. See the following link and the the related screen shots:
[signorini.html](https://thelfer.github.io/tfel/web/signorini.html)

![image](https://github.com/thelfer/MFrontGallery/assets/61900614/9facde3f-75e7-48cd-aef8-6e1d85d9d978)
![image](https://github.com/thelfer/MFrontGallery/assets/61900614/d00917f6-ca61-4c98-8dfe-122082980164)

Instead of 
`2 C20 (\bar{I1} - 3)^2`
it should be
`C20 (\bar{I1} - 3)^2`
So, the derivative versus `\bar{I1}` would be
`2 C20 (\bar{I1} - 3)`

**Comment by octave-user** [comment]
See also this pull request:
[octave-user:Signorini-strain-energy](https://github.com/thelfer/MFrontGallery/pull/50)

**Comment by thelfer** [comment]
Merged ! Thanks !

**Comment by thelfer** [comment]
Documentation fixed: https://github.com/thelfer/tfel/issues/550
